-- SGUNMS Login History
-- Run once in Supabase SQL Editor.

create table if not exists public.login_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text not null,
  name text,
  login_at timestamptz not null default now(),
  device text,
  browser text,
  os text,
  screen_size text,
  user_agent text
);

create index if not exists login_logs_user_id_idx on public.login_logs(user_id);
create index if not exists login_logs_login_at_idx on public.login_logs(login_at desc);

alter table public.login_logs enable row level security;
alter table public.login_logs force row level security;

drop policy if exists "login_logs_insert_own" on public.login_logs;
drop policy if exists "login_logs_admin_read" on public.login_logs;

-- A signed-in user may create a login record only for their own auth id/email.
create policy "login_logs_insert_own"
on public.login_logs for insert to authenticated
with check (
  user_id = auth.uid()
  and lower(email) = lower(coalesce(auth.jwt()->>'email',''))
);

-- Only the SGUNMS super-admin can read login history.
create policy "login_logs_admin_read"
on public.login_logs for select to authenticated
using (
  lower(coalesce(auth.jwt()->>'email','')) = 'shashi841505@gmail.com'
);

-- No client-side update/delete policies: login history is append-only from the app.

comment on table public.login_logs is 'SGUNMS successful login history';
