(function(){'use strict';
const KEY='sgunmsRemindersV2', FAMILY_KEY='sgunmsFamilyDataV1';
const TYPES=[['birthday','🎂','Birthday','परिवार के सदस्य का जन्मदिन'],['anniversary','💍','Anniversary','शादी की सालगिरह'],['engagement_anniversary','💑','Engagement Anniversary','सगाई की सालगिरह'],['death_anniversary','🕯️','पुण्यतिथि','दिवंगत परिवारजन की पुण्यतिथि'],['birth','👶','Birth','बच्चे के जन्म की याद'],['griha_pravesh','🏠','Griha Pravesh','गृह प्रवेश की सालगिरह'],['wedding','💒','Wedding','शादी की तारीख'],['tilak','🎉','Tilak','तिलक कार्यक्रम की तारीख'],['baraat','🥁','Baraat','बारात की तारीख'],['reception','🍽️','Reception','रिसेप्शन की तारीख'],['sagun','🎁','Sagun','सगुन देने/लेने की याद'],['exam_school','📚','Exam/School','बच्चों की परीक्षा या स्कूल'],['appointment','🏥','Appointment','डॉक्टर/अन्य अपॉइंटमेंट'],['travel','✈️','Travel','यात्रा की तारीख'],['custom','📅','Custom Reminder','अपना कोई भी Reminder']];
const q=new URLSearchParams(location.search), type=q.get('type')||'birthday', info=TYPES.find(x=>x[0]===type)||TYPES[0];
let items=(()=>{try{return JSON.parse(localStorage.getItem(KEY))||[]}catch(e){return[]}})();
function family(){try{return JSON.parse(localStorage.getItem(FAMILY_KEY))||{members:[]}}catch(e){return{members:[]}}}
function esc(v){return String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[s]))}
function parse(v){if(!v)return null;const a=String(v).slice(0,10).split('-').map(Number);return a.length===3&&!a.some(Number.isNaN)?new Date(a[0],a[1]-1,a[2]):null}
function next(x){const d=parse(x.date);if(!d)return null;if(!x.yearly)return d;const n=new Date(),r=new Date(n.getFullYear(),d.getMonth(),d.getDate());return r<new Date(n.getFullYear(),n.getMonth(),n.getDate())?new Date(n.getFullYear()+1,d.getMonth(),d.getDate()):r}
function days(d){return Math.round((new Date(d.getFullYear(),d.getMonth(),d.getDate())-new Date(new Date().getFullYear(),new Date().getMonth(),new Date().getDate()))/86400000)}
function familyItems(){const out=[];(family().members||[]).forEach(m=>{if(type==='birthday'&&m.birthday)out.push({id:'family-b-'+m.id,type,title:(m.name||'सदस्य')+' का Birthday',date:'2000-'+String(m.birthday).slice(-5),yearly:true,source:'family'});if(type==='anniversary'&&m.anniversary)out.push({id:'family-a-'+m.id,type,title:(m.name||'सदस्य')+' की Anniversary',date:'2000-'+String(m.anniversary).slice(-5),yearly:true,source:'family'});});return out}
function render(){const all=[...familyItems(),...items.filter(x=>x.type===type)];const seen=new Set();const arr=all.filter(x=>{if(seen.has(x.id))return false;seen.add(x.id);return true}).map(x=>({...x,occ:next(x)})).sort((a,b)=>(a.occ||9e15)-(b.occ||9e15));document.getElementById('listTitle').textContent=info[1]+' '+info[2];document.getElementById('listSubtitle').textContent=info[3];document.getElementById('listHeading').textContent=info[1]+' '+info[2]+' — पूरी सूची';document.getElementById('listCount').textContent=arr.length+' reminder';document.getElementById('listItems').innerHTML=arr.length?arr.map(x=>{const n=days(x.occ),left=n===0?'आज':n===1?'1 day left':n>1?n+' day left':Math.abs(n)+' दिन पहले';return `<article class="detail-row"><div class="icon">${info[1]}</div><div><strong>${esc(x.title)}</strong><div class="muted">${x.occ.toLocaleDateString('hi-IN',{day:'2-digit',month:'long',year:'numeric'})} • ${left}${x.source==='family'?' • Family':''}</div></div>${x.source==='family'?'<a class="mini" href="family.html">✏️ Family Edit</a>':'<button class="mini" data-del="'+esc(x.id)+'">🗑️ Delete</button>'}</article>`}).join(''):'<div class="empty">इस category में अभी कोई reminder नहीं है।</div>'}
function openModal(){document.getElementById('remModal').hidden=false;document.getElementById('remType').innerHTML=TYPES.map(x=>`<option value="${x[0]}" ${x[0]===type?'selected':''}>${x[1]} ${x[2]}</option>`).join('')}
function close(){document.getElementById('remModal').hidden=true}
document.addEventListener('DOMContentLoaded',()=>{render();document.getElementById('listAddBtn').onclick=openModal;document.querySelectorAll('[data-close]').forEach(x=>x.onclick=close);document.getElementById('listItems').onclick=e=>{const b=e.target.closest('[data-del]');if(b){items=items.filter(x=>x.id!==b.dataset.del);localStorage.setItem(KEY,JSON.stringify(items));render()}};document.getElementById('remForm').onsubmit=e=>{e.preventDefault();items.push({id:'rem_'+Date.now().toString(36),type,date:document.getElementById('remDate').value,title:document.getElementById('remTitle').value.trim(),time:document.getElementById('remTime').value,allDay:document.getElementById('allDay').checked,yearly:document.getElementById('repeatYearly').checked,notes:document.getElementById('remNotes').value.trim(),alert:document.getElementById('remAlert').value,done:false});localStorage.setItem(KEY,JSON.stringify(items));close();render()}})
})();
